name: Docker


on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: image


jobs:
  # Run tests.
  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest
    
    steps:
      - name: SSH Execute Commands
        uses: JimCronqvist/action-ssh@0.1.1
        with:
          command: ls
          hosts: ${{ secrets.HOSTS }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.KEY }}
          debug: true
          
        
        
  

    
